name: Go PR Check

on:
  pull_request:
    branches: [main]

jobs:
  lint-test-build:
    name: Lint, Vet & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Verify go.mod is tidy
        run: go mod tidy && git diff --exit-code

      - name: Run gofmt
        run: test -z "$(gofmt -s -l .)" || (gofmt -s -l . && exit 1)

      - name: Run go vet
        run: go vet ./...

      - name: Run tests with coverage
        run: go test -v -coverprofile=coverage.out ./...

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.out
